FROM golang:1.21.1-bookworm
WORKDIR /gocoderunner
COPY ./code/{imageName}.go /gocoderunner
RUN go mod init {imageName}
RUN go mod download
RUN CGO_ENABLED=0 go build -o {imageName}
RUN chmod +x /gocoderunner/{imageName}
ENTRYPOINT [ "/gocoderunner/{imageName}" ]
